# Generated by Django 3.2.6 on 2021-11-25 05:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='имя')),
                ('short_desc', models.CharField(blank=True, max_length=300, verbose_name='краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='обновлено')),
                ('download_counter', models.IntegerField(blank=True, default=0, verbose_name='кол-во скачиваний')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitersk.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='имя')),
                ('link', models.CharField(default='index', max_length=50, verbose_name='Ссылка')),
                ('is_avaliable', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='имя файла')),
                ('file', models.FileField(blank=True, upload_to='files/', verbose_name='Загрузить файл')),
                ('server_files', models.FilePathField(blank=True, path='media/files/', verbose_name='Выбрать файл на сервере')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitersk.news', verbose_name='Материал')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitersk.parent'),
        ),
    ]
