# Generated by Django 3.2.6 on 2021-11-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitersk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='name',
            field=models.CharField(max_length=300, verbose_name='имя файла'),
        ),
    ]
