# Generated by Django 3.2.6 on 2021-10-22 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitersk', '0004_auto_20211019_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
