# Generated by Django 3.2.6 on 2021-11-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitersk', '0007_news_download_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AddField(
            model_name='parent',
            name='is_avaliable',
            field=models.BooleanField(default=True, verbose_name='Опубликовано(Да/Нет)'),
        ),
        migrations.AddField(
            model_name='parent',
            name='link',
            field=models.CharField(default='index', max_length=50, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
