# Generated by Django 3.2.6 on 2021-10-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitersk', '0002_category_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_desc',
            field=models.CharField(blank=True, max_length=150, verbose_name='краткое описание продукта'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='имя'),
        ),
    ]
