# Generated by Django 3.2.6 on 2021-10-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitersk', '0003_auto_20211019_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_desc',
            field=models.CharField(blank=True, max_length=300, verbose_name='краткое описание продукта'),
        ),
    ]
