# Generated by Django 3.2.6 on 2021-10-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitersk', '0005_auto_20211022_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='files',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
