# Generated by Django 3.2.6 on 2021-10-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitersk', '0006_news_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='download_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
